---
- name: Setting up hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname_fqdn_full }}"

- name: Update the IPv4 part of hosts file
  become: true
  ansible.builtin.lineinfile:
    dest: "{{ hostname_hosts_file_location }}"
    regexp: "^127.0.0.1"
    # yamllint disable-line rule:line-length
    line: "127.0.0.1{{ '\t' }}{{ hostname_fqdn_full }}{{ '\t' }}{% if hostname_fqdn_full != hostname_fqdn_short %}{{ hostname_fqdn_short }}{{ '\t' }}{% endif %}localhost localhost.localdomain localhost4 localhost4.localdomain4"
    state: present
    backup: "{{ hostname_hosts_backup }}"
  when: hostname_hosts_ipv4_enabled

- name: Update the IPv6 part of hosts file
  become: true
  ansible.builtin.lineinfile:
    dest: "{{ hostname_hosts_file_location }}"
    regexp: "^::1"
    # yamllint disable-line rule:line-length
    line: "::1{{ '\t\t' }}{{ hostname_fqdn_full }}{% if hostname_fqdn_full != hostname_fqdn_short %}{{ '\t' }}{{ hostname_fqdn_short }}{% endif %}{{ '\t' }}localhost localhost.localdomain localhost6 localhost4.localdomain6 ip6-localhost ip6-loopback"
    state: present
  when: hostname_hosts_ipv6_enabled
